CUDA_VISIBLE_DEVICES=3 python src/train_bash.py\
    --stage sft \
    --model_name_or_path /raid/gzy/qwen/Qwen-14B-Chat/ \
    --do_train \
    --dataset 4_chat_train \
    --template Qwen-14B-Chat \
    --finetuning_type lora \
    --lora_target c_attn \
    --output_dir /raid/gzy/qwen/checkpoint/chat_4 \
    --overwrite_cache \
    --per_device_train_batch_size 16 \
    --gradient_accumulation_steps 4 \
    --lr_scheduler_type cosine \
    --logging_steps 10 \
    --save_steps 10 \
    --learning_rate 1e-4 \
    --num_train_epochs 10 \
    --plot_loss \
    --bf16 