CUDA_VISIBLE_DEVICES=3 python src/train_bash.py\
    --stage sft \
    --dataset train \
    --model_name_or_path /raid/gzy/chatglm3/chatglm3-6b/ \
    --do_train \
    --template chatglm3 \
    --finetuning_type lora \
    --lora_target query_key_value \
    --output_dir /raid/gzy/chatglm3/checkpoint_bot_1_fin/ \
    --overwrite_cache \
    --per_device_train_batch_size 16 \
    --gradient_accumulation_steps 4 \
    --lr_scheduler_type cosine \
    --logging_steps 10 \
    --save_steps 30 \
    --learning_rate 1e-5 \
    --num_train_epochs 30 \
    --plot_loss \
    --fp16 